theme: jekyll-theme-bojekylls

# Site wide configuration
destination: docs
url: 'https://rossgodwin.com'
baseurl: ''
lang: en

# Analytics
#google_analytics_measurement_id: G-CNWKCECNVN

# Jekyll configuration
show_drafts: false
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
include:
  - _pages
exclude:
  - .bundle
  - .jekyll-cache
  - .gitignore
  - .project
  - _drafts
  - docs/
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/bundle/

excerpt_separator: <!--more-->

sass:
  style: :compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

collections_dir: collections
collections:
  resumes:
    output: true
    permalink: /resumes/:path/

# Plugins
gems:
  - jekyll-feed
  - jekyll-liquify

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      include-seo: false
      include-seo-og: false
      show-page-loading-overlay: false
      page-loading-overlay-id: page-loading-overlay-id
  - scope:
      type: resumes
    values:
      include-seo: true
      categories: [resumes]
  - scope:
      path: assets/*
    values:
      sitemap: false

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 5
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  tags:
    enabled: false
    layouts:
      - autopage_tags.html
    permalink: /tag/:tag
  categories:
    enabled: false
    layouts:
      - autopage_category.html
  collections:
    enabled: false
    slugify:
      mode: 'ascii'
      cased: true

# Plugin: Redirect (jekyll-redirect-from)
redirect_from:
  json: false